version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: ./setup/Dockerfile

    volumes:
      - ./mount:/home/jovyan/mount
    ports:
      - 8888:8888
    command: "start-notebook.sh --NotebookApp.token="
